cart/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add/<item_id>', views.add_to_cart, name="add_to_cart"),
    path('adjust/<item_id>/', views.adjust_cart, name="adjust_cart"),
    path('remove/<item_id>/', views.remove_item, name="remove_item"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plant_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('review/', include('review.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.products_all, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255)
    friendly_name = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    category = models.ForeignKey('Category',
        null=True, blank=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=255)
    friendly_name = models.CharField(max_length=255, null=True, blank=True)
    sku = models.CharField(max_length=255, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    description = models.TextField(blank=True)
    product_image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name


class Image(models.Model):
    name = models.CharField(max_length=300)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/', default='default.jpg')

    def __str__(self):
        return self.name

products/forms.py
from django import forms
from .models import Product, Category, Image


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names


# class ImageForm(forms.ModelForm):
    
#     class Meta:
#         model = Image
#         fields = '__all__'
    
#     def __init__(self, *args, **kwargs):
#          super().__init__(*args, **kwargs)
#          products = Product.objects.all()
         

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .models import Product, Image, Category
from .forms import ProductForm

# Create your views here.


def products_all(request):
    """ A view to show all products """

    products = Product.objects.all()
    query = None
    categories = None

    if request.GET:
        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "Please enter a valid search criteria")
                return redirect(reverse('products'))

            queries = Q(name__icontains=query) | Q(
                description__icontains=query)
            products = products.filter(queries)

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ A view to show individual product details """

    product = get_object_or_404(Product, pk=product_id)

    context = {
        'product': product,
    }

    return render(request, 'products/product_detail.html', context)


def images_all(request, id):
    """
    A View to display product detailed image in \
        the product detail page
    """
    product = get_object_or_404(Product, id=id)
    images = Image.objects.filter(product=product)

    context = {
        'images': images,
        'product': product,
    }
    return render(request, 'products/product_detail.html', context)


@login_required
def add_product(request):
    """
    Add a new product to the store (superuser)
    """
    if not request.user.is_superuser:
        messages.error(request, 'You dont have access to this page')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added new product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to add new product.')
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """
    Edit an existing product.
    """
    if not request.user.is_superuser:
        messages.error(request, 'You dont have access to this page')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        images = Image.objects.filter(product=product)
        if form.is_valid():
            form.save()
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to update product.')
    else:
        form = ProductForm(instance=product)
     
    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """ Delete a product - admin """
    if not request.user.is_superuser:
        messages.error(request, 'You dont have access to this page')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!--Code borrowed from: https://bbbootstrap.com/snippets/bootstrap-ecommerce-shopping-cart-item-summary-44021562-->
<div class="album py-5 bg-light">
    <div class="row">
        <div class="col">
            <div class="title">
                <div class="row">
                    <div class="col">
                        <h4 class="text-center"><b>Product Management</b></h4>
                        <h5 class="text-center"><b>Add Product</b></h5>
                    </div>
                </div>
            </div>
            <div class="row border-top border-bottom">
                <div class="col-8 md-6">
                    <h5 class="text-muted text-center">
                        Add a product by filling out the form below.
                    </h5>
                    <form action="{% url 'add_product' %}" method="POST" class="form mb-4"
                        enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form | crispy }}
                        {{ images | crispy }}
                        <div class="row">
                            <div class="col-6"><a href="{% url 'products' %}"
                                    class="btn btn-outline-secondary btn-lg">View all Products</a></div>
                            <div class="col-6"><button class="btn btn-outline-success" type="submit">Add
                                    Product</button>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>

{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!--Base code borrowed from: https://bbbootstrap.com/snippets/bootstrap-ecommerce-shopping-cart-item-summary-44021562-->
<div class="album py-5 bg-light">
    <div class="row">
        <div class="col">
            <div class="title">
                <div class="row">
                    <div class="col">
                        <h4 class="text-center"><b>Product Management</b></h4>
                        <h5 class="text-center"><b>Edit Product</b></h5>
                    </div>
                </div>
            </div>
            <div class="row border-top border-bottom">
                <div class="col-8 md-6">
                    <h5 class="text-muted text-center">
                        Add a product by filling out the form below.
                    </h5>
                    <form action="{% url 'edit_product' product.id %}" method="POST" class="form mb-4"
                        enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form | crispy }}

                        <div class="form-group m-3">
                        </div>
                        <div class="row">
                            <div class="col-6"><a href="{% url 'products' %}"
                                    class="btn btn-outline-secondary btn-lg">View all Products</a></div>
                            <div class="col-6"><button class="btn btn-outline-success" type="submit">Update
                                    Product</button>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>

{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}
{% block extra_title %}| {{ product.friendly_name }}{% endblock %}

{% block content %}

<div class="album py-5 bg-light">
    <div class="container-fluid">
        <main class="pt-5">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-12 shadow bg-body rounded">
                    <div class="row justify-content-between">
                        <div class="card col-12" style="width: 12rem;">
                            <img src="{{ product.product_image.url }}" class="card-img-top" alt="Product detailed image"
                                width="200" height="200">
                            {% for images in product.image_set.all %}
                            <img src="{{ images.image.url }}" class="card-img-top" alt="Product detailed image"
                                width="200" height="200">
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-6">
                    <h1>{{ product.friendly_name }}</h1>
                    <h4>{{ product.category }}</h4>
                    <div class="col-12"><span class="h4 fw-bold">$ {{ product.price }}</span></div>
                    <p>{{ product.description|slice:"1000" }}</p>
                    <small class="text-muted">
                        {% if request.user.is_superuser %}
                        <a href="{% url 'edit_product' product.id %}" class="">Edit</a>
                        <a href="{% url 'delete_product' product.id %}" class="text-danger">Delete</a>
                    </small>
                    {% endif %}
                    <form action="{% url 'add_to_cart' product.id %}" method="POST">
                        {% csrf_token %}
                        <div class="input-group prepend">
                            <strong><label for="select">Quantity</label></strong>
                            <div class="input-group">
                                <div class="col-3">
                                    <!--- Borrowed partly from the Boutiqe Ado project-->
                                    <div class="row">
                                        <div class="input-group-prepend col-6">
                                            <button class="decrement-qty btn rounded" data-item_id="{{ product.id }}"
                                                id="decrement-qty_{{ product.id }}">
                                                -
                                            </button>
                                        </div>
                                        <div class="input-group-append col-6">
                                            <button class="increment-qty btn rounded" data-item_id="{{ product.id }}"
                                                id="increment-qty_{{ product.id }}">
                                                +
                                            </button>
                                        </div>
                                    </div>
                                    <input class="form-control qty_input" type="number" name="quantity" value="1"
                                        min="1" max="20" data-item_id="{{ product.id }}" id="id_qty_{{ product.id }}">
                                </div>
                            </div>
                        </div>
                </div>
            </div>
    </div>
    <div class="row justify-content-end">
        <div class="col-6">
            <input type="submit" class="btn btn-outline-success" value="Add to cart">
            <input type="hidden" name="redirect_url" value="{{ request.path }}">
        </div>
    </div>
    </form>
    <div class="row">
        <h3 class="text-black">Review this!</h3>
        {% if user.is_authenticated %}
        <div class="col-6 md-6 sm-12">
            <form action="{% url 'add_review' product.id %}" method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                <h5>Add your review below.</h5>
                <div class="form-group">
                    <input type="text" class="form-control" name="subject" placeholder="Title" required>
                    <br>
                    <textarea name="review" rows="10" class="form-control" placeholder="Your review"
                        required></textarea>
                    <br>
                    <button class="btn btn-success" type="submit">Add your review!</button>
                </div>
            </form>
        </div>
        {% else %}
        <div class="col-6">
            <h5 class="text-black">Log in to add a review!</h5>
            <a class="btn" href="{% url 'account_login' %}">Log In</a>
            <a class="btn" href="{% url 'account_signup' %}">Register</a>
        </div>
        {% endif %}
        <div class="col-6">
            <h3 class="text-black">Product Reviews</h3>
            {% for review in product.review.all %}
            <div class="col-6 col-lg-12">
                <p>{{review.review}}</p>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

</div>
</div>
</div>
</div>
</main>
</div>
</div>
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}

products/templates/products/products.html
{% extends "base.html" %}
{% load static %}
{% block extra_title %}| All Products{% endblock %}

{% block content %}
<!---Code copied from Bootstap documentation: "https://getbootstrap.com/docs/4.0/examples/album/"-->
<div class="album py-5 bg-light">
  <div class="container">

    <div class="row">
      {% for product in products %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          {% if product.product_image %}
          <img class="card-img-top" src="{{ product.product_image.url }}" alt="Card image cap" width="400" height="400">
          {% else %}
          <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail"
            alt="Card image cap">
          {% endif %}
          <div class="card-body">
            <h4 class="d-flex justify-content-between align-items-center">{{ product.friendly_name }}</h4>
            <p class="card-text justify-content-between align-items-center">{{ product.category }}</p>
            <p class="card-text">{{ product.description|slice:"50" }}...</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="{% url 'product_detail' product.id %}" class="btn btn-outline-secondary" role="button">View
                  Product</a>
              </div>
              <div class="row mt-3">
                <small class="text-muted">
                  {% if request.user.is_superuser %}
                  <a href="{% url 'edit_product' product.id %}">Edit</a>
                  <a href="{% url 'delete_product' product.id %}" class="text-danger">Delete</a>
                  {% endif %}
                </small>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  {% endblock %}

  {% load static %}